import { Brand, ContentPillar, ScriptTemplate } from "./types";

export const seedBrands: Brand[] = [
  {
    id: "brand_chamei",
    name: "Chamei",
    slug: "chamei",
    logoEmoji: "📞",
    description: "Marketplace de serviços. Encontre profissionais confiáveis pelo WhatsApp.",
    tone: "Humor + indignação com serviço ruim. Linguagem popular, direta.",
    targetAudience: "Pessoas que precisam de serviços domésticos (25-55 anos)",
    competitors: "Google Empresas (precisa ligar ou salvar número pra mandar WhatsApp, UX ruim), Habitissimo (cobra do profissional, processo lento), indicação boca-a-boca (demorado, sem garantia)",
    painPoints: "No Google tem que ligar ou copiar número pra WhatsApp (fricção), não sabe se o profissional é bom até contratar, processo lento de pedir orçamento, profissional que não responde ou não aparece",
    colors: { primary: "#2563EB", secondary: "#1E40AF" },
    platforms: ["instagram", "tiktok"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "brand_delas",
    name: "Delas Club",
    slug: "delas",
    logoEmoji: "💅",
    description: "Comunidade feminina de beleza e bem-estar. Profissionais indicadas por mulheres.",
    tone: "Humor feminino, relatable, empoderamento. Linguagem de grupo de amigas.",
    targetAudience: "Mulheres 20-45 que buscam serviços de beleza",
    competitors: "Apps genéricos que não entendem beleza, indicação aleatória do Instagram",
    painPoints: "Manicure que destruiu a unha, esteticista sem qualificação, preço surpresa",
    colors: { primary: "#E11D48", secondary: "#BE123C" },
    platforms: ["instagram", "tiktok"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "brand_soninho",
    name: "Soninho",
    slug: "soninho",
    logoEmoji: "🌙",
    description: "App de rotina e histórias para crianças. Conteúdo calmo adaptado ao ritmo do dia.",
    tone: "Empático com pais, humor sobre caos da criação. Carinhoso.",
    targetAudience: "Pais de crianças 2-10 anos",
    competitors: "YouTube Kids (conteúdo lixo), apps com propaganda, telas sem controle",
    painPoints: "Filho que não dorme, briga pra largar o celular, conteúdo impróprio",
    colors: { primary: "#7B6CF6", secondary: "#1A1A2E" },
    platforms: ["instagram", "tiktok", "youtube"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "brand_simplifica",
    name: "SimplificaApp",
    slug: "simplifica",
    logoEmoji: "👴",
    description: "Transforma qualquer site em interface simples e acessível para idosos e crianças.",
    tone: "Emoção + humor com tecnologia. Amor pelos avós. Indignação com sites complicados.",
    targetAudience: "Filhos/netos de idosos (30-50), cuidadores",
    competitors: "Sites do governo inacessíveis, bancos com apps confusos",
    painPoints: "Avó que não consegue pagar conta online, idoso excluído digitalmente",
    colors: { primary: "#059669", secondary: "#047857" },
    platforms: ["instagram", "tiktok", "youtube"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "brand_spark",
    name: "Spark",
    slug: "spark",
    logoEmoji: "🔥",
    description: "App de relacionamentos com experiências estruturadas pós-match.",
    tone: "Humor ácido sobre dating, sarcasmo, relatable. Gen Z/Millennial.",
    targetAudience: "Jovens 20-35 cansados de apps de namoro",
    competitors: "Tinder (superficial), Bumble (mesmo problema), Hinge (tentou mas falhou)",
    painPoints: "Match → oi → silêncio, ghosting, conversas mortas, catfish",
    colors: { primary: "#F97316", secondary: "#0F0F0F" },
    platforms: ["instagram", "tiktok"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "brand_blackcube",
    name: "Blackcube",
    slug: "blackcube",
    logoEmoji: "◼️",
    description: "Agência de automação digital. Builds que entregam resultado, não slides.",
    tone: "Autoridade + provocação. Anti-agência tradicional. Dados > opinião.",
    targetAudience: "Empreendedores, PMEs, startups early-stage",
    competitors: "Agências tradicionais (lentas, caras), freelancers (inconsistentes)",
    painPoints: "Pagou R$5k num site de 2010, 6 meses pra entregar landing page, zero dados",
    colors: { primary: "#FFFFFF", secondary: "#000000" },
    platforms: ["instagram", "linkedin"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "brand_squad",
    name: "Squad Performance",
    slug: "squad",
    logoEmoji: "🎯",
    description: "SaaS de gestão de performance para PMEs. Avaliações de desempenho, metas, ciclos de feedback e relatórios — tudo simples e em português.",
    tone: "Profissional mas acessível. Humor corporativo leve. Anti-burocracia. Fala a língua do gestor brasileiro que sofre com planilha.",
    targetAudience: "Gestores de PMEs (10-200 funcionários), donos de empresa, RH de pequenas empresas, líderes de equipe que querem dar feedback sem drama",
    competitors: "Planilhas de Excel/Google Sheets (todo mundo usa, ninguém gosta), Qulture.Rocks (caro, complexo demais pra PME), Feedz (focado em enterprise), avaliação informal no 1:1 (sem registro, sem dados), não fazer nada (a maioria das PMEs)",
    painPoints: "Avaliação de desempenho feita em planilha que ninguém preenche, gestor que não sabe dar feedback construtivo, funcionário que não sabe onde precisa melhorar, zero visibilidade de quem performa e quem não, perder talento porque nunca deu reconhecimento, RH pedindo avaliação e ninguém responde, reunião de feedback que vira bate-papo sem resultado",
    colors: { primary: "#1B3A6B", secondary: "#2563EB" },
    platforms: ["instagram", "tiktok", "linkedin"],
    createdAt: new Date().toISOString(),
  },
];

export const seedPillars: ContentPillar[] = [
  {
    id: "pillar_dor",
    name: "DOR",
    slug: "dor",
    description: "Conteúdo que expõe a frustração do público. Faz a pessoa sentir que você entende a dor dela.",
    emotion: "Frustração / Indignação / Identificação",
  },
  {
    id: "pillar_solucao",
    name: "SOLUÇÃO",
    slug: "solucao",
    description: "Mostra como o produto/serviço resolve o problema. Transforma dor em esperança.",
    emotion: "Alívio / Curiosidade / Desejo",
  },
  {
    id: "pillar_social_proof",
    name: "SOCIAL PROOF",
    slug: "social-proof",
    description: "Prova que outras pessoas já usaram e aprovaram. Depoimentos, números, resultados.",
    emotion: "Confiança / FOMO / Validação",
  },
];

export const seedTemplates: ScriptTemplate[] = [
  // DOR templates
  {
    id: "tmpl_pov_frustracao",
    name: 'POV: [situação frustrante]',
    slug: "pov-frustracao",
    pillarId: "pillar_dor",
    structure: "HOOK: POV: [situação do público]\n[TEXTO NA TELA: contexto]\n[Reação exagerada/humor]\n[Plot twist mostrando a dor]\n[CORTE para solução (teaser)]",
    hookPattern: "POV: você [ação que gera frustração]",
    ctaPattern: "Cansou disso? Link na bio.",
    format: "reels",
    duration: 30,
    examples: 'POV: você pediu orçamento no GetNinjas\n[3 dias depois... nada]\n[7 dias depois... teia de aranha]\nEnquanto isso no Chamei: 5 orçamentos em 10 min',
  },
  {
    id: "tmpl_ninguem_fala",
    name: "Ninguém fala sobre...",
    slug: "ninguem-fala",
    pillarId: "pillar_dor",
    structure: "HOOK: Ninguém fala sobre [problema escondido]\n[Revelação 1 - dado ou fato]\n[Revelação 2 - consequência]\n[Revelação 3 - como isso afeta VOCÊ]\n[Teaser da solução]",
    hookPattern: "Ninguém fala sobre [problema do nicho]",
    ctaPattern: "Mas a gente fala. E resolve. Link na bio.",
    format: "reels",
    duration: 45,
    examples: "Ninguém fala sobre o quanto você paga por leads que nunca respondem.\nR$80 por contato. Que não atende. Que já contratou outro.",
  },
  {
    id: "tmpl_tipos",
    name: "Tipos de [profissional ruim]",
    slug: "tipos",
    pillarId: "pillar_dor",
    structure: "HOOK: X tipos de [profissional/situação] que você já encontrou\n[Tipo 1 - relatable e engraçado]\n[Tipo 2 - irritante]\n[Tipo 3 - absurdo]\n[Tipo 4 - o bom (sua solução)]",
    hookPattern: "X tipos de [categoria] que todo mundo conhece",
    ctaPattern: "Qual tipo você já pegou? Comenta aí 👇",
    format: "reels",
    duration: 45,
    examples: "5 tipos de encanador:\n1. O sumido (aceita e some)\n2. O orçamento surpresa (R$200 vira R$800)\n3. O que resolve com durex",
  },
  {
    id: "tmpl_expectativa_realidade",
    name: "Expectativa vs Realidade",
    slug: "expectativa-realidade",
    pillarId: "pillar_dor",
    structure: "HOOK: [Situação] Expectativa vs Realidade\n[Split screen ou antes/depois]\n[Expectativa bonita]\n[Realidade decepcionante]\n[Repeat 2-3x]\n[Sua solução como plot twist]",
    hookPattern: "Expectativa vs Realidade: [situação]",
    ctaPattern: "Chega de decepção. [Marca] resolve.",
    format: "reels",
    duration: 30,
    examples: "Expectativa: agendar um eletricista online\nRealidade: 3 apps, 2 dias, ninguém apareceu",
  },
  {
    id: "tmpl_red_flags",
    name: "Red flags de [concorrente]",
    slug: "red-flags",
    pillarId: "pillar_dor",
    structure: "HOOK: Red flags de [concorrente/categoria] 🚩\n[Flag 1 com evidência]\n[Flag 2 com evidência]\n[Flag 3 - a pior]\n[O que fazer em vez disso]",
    hookPattern: "Red flags de [concorrente] 🚩",
    ctaPattern: "Se identificou? Tem solução. Link na bio.",
    format: "reels",
    duration: 30,
    examples: "Red flags do GetNinjas 🚩\n- Cobra pra ver contato\n- Profissional nunca responde\n- Zero garantia de qualidade",
  },
  // SOLUÇÃO templates
  {
    id: "tmpl_before_after",
    name: "Before/After",
    slug: "before-after",
    pillarId: "pillar_solucao",
    structure: "HOOK: Antes vs Depois de [usar produto]\n[Antes: cena de caos/frustração]\n[Transição dramática]\n[Depois: tudo resolvido, paz]\n[Mostrar o produto em ação]",
    hookPattern: "Antes vs Depois de conhecer [marca]",
    ctaPattern: "Quer essa transformação? Link na bio.",
    format: "reels",
    duration: 30,
    examples: "Antes: ligando pra 10 encanadores, ninguém atende\nDepois: abri o Chamei, 5 orçamentos em 10 minutos pelo WhatsApp",
  },
  {
    id: "tmpl_3_passos",
    name: "Como [ação] em 3 passos",
    slug: "3-passos",
    pillarId: "pillar_solucao",
    structure: "HOOK: Como [resolver problema] em 3 passos\n[Passo 1 - simples, rápido]\n[Passo 2 - a mágica acontece]\n[Passo 3 - resultado final]\n[CTA direto]",
    hookPattern: "Como [ação] em 3 passos (sem [obstáculo])",
    ctaPattern: "Simples assim. Testa agora: link na bio.",
    format: "reels",
    duration: 30,
    examples: "Como encontrar um eletricista confiável em 3 passos:\n1. Abre o Chamei\n2. Descreve o serviço\n3. Recebe orçamentos pelo WhatsApp",
  },
  {
    id: "tmpl_descobri",
    name: "Eu descobri que...",
    slug: "descobri",
    pillarId: "pillar_solucao",
    structure: "HOOK: Eu descobri que [revelação]\n[Contexto da descoberta]\n[O que mudou na minha vida]\n[Prova/demonstração]\n[Convite para experimentar]",
    hookPattern: "Eu descobri que [fato surpreendente sobre o nicho]",
    ctaPattern: "Descobre você também. Link na bio.",
    format: "reels",
    duration: 45,
    examples: "Eu descobri que dá pra receber 5 orçamentos de encanador em 10 minutos.\nSem pagar nada. Sem app. Só pelo WhatsApp.",
  },
  {
    id: "tmpl_app_resolve",
    name: "O app que [resolve dor]",
    slug: "app-resolve",
    pillarId: "pillar_solucao",
    structure: "HOOK: Existe um app que [resolve dor específica]\n[Mostra o problema comum]\n[Mostra o app funcionando]\n[Resultado impressionante]\n[CTA urgente]",
    hookPattern: "Existe um app que [benefício inacreditável]",
    ctaPattern: "Baixa agora antes que todo mundo descubra.",
    format: "tiktok",
    duration: 30,
    examples: "Existe um app que te mostra se o site do banco tá confuso pro seu avô.\nE transforma em interface simples. Na hora.",
  },
  {
    id: "tmpl_teste_comparacao",
    name: "Teste: [marca] vs [concorrente]",
    slug: "teste-comparacao",
    pillarId: "pillar_solucao",
    structure: "HOOK: Testei [marca] vs [concorrente]. Olha o resultado.\n[Setup do teste]\n[Concorrente fazendo o processo]\n[Marca fazendo o processo]\n[Resultado lado a lado]\n[Veredito]",
    hookPattern: "Testei [marca] vs [concorrente] e olha...",
    ctaPattern: "Resultado fala por si. Link na bio.",
    format: "reels",
    duration: 60,
    examples: "Testei Chamei vs GetNinjas pra achar um pintor.\nGetNinjas: R$80, 3 dias, 1 resposta.\nChamei: grátis, 10 min, 5 orçamentos.",
  },
  // SOCIAL PROOF templates
  {
    id: "tmpl_depoimento",
    name: "Depoimento real",
    slug: "depoimento",
    pillarId: "pillar_social_proof",
    structure: "HOOK: [Nome] tentou [X] e quase desistiu. Até que...\n[Contexto da pessoa]\n[A dor que ela vivia]\n[Descoberta da solução]\n[Resultado concreto]\n[Fala dela (quote)]",
    hookPattern: "[Nome] estava [situação ruim]. Até conhecer [marca].",
    ctaPattern: "Quer o mesmo resultado? Link na bio.",
    format: "reels",
    duration: 45,
    examples: "A Carla precisava de uma manicure pro casamento.\n3 cancelamentos em cima da hora.\nAchou a Delas Club. Encontrou a Ana em 5 min.\n'Melhor unha da minha vida' — Carla",
  },
  {
    id: "tmpl_numero_pessoas",
    name: "[Número] pessoas já [ação]",
    slug: "numero-pessoas",
    pillarId: "pillar_social_proof",
    structure: "HOOK: [Número impressionante] pessoas já [ação]\n[Visualização do número]\n[O que essas pessoas tinham em comum]\n[Depoimentos rápidos (3-4)]\n[Convite para ser o próximo]",
    hookPattern: "+[número] pessoas já [ação com a marca]",
    ctaPattern: "Falta só você. Link na bio.",
    format: "reels",
    duration: 30,
    examples: "+8.000 profissionais já estão no Chamei.\nEletricistas, encanadores, pintores, diaristas.\nTodos recebendo clientes pelo WhatsApp. Grátis.",
  },
  {
    id: "tmpl_olha_resultado",
    name: "Olha o que chegou...",
    slug: "olha-resultado",
    pillarId: "pillar_social_proof",
    structure: "HOOK: Olha o que chegou no meu WhatsApp...\n[Mostra prints/resultados]\n[Reação genuína]\n[Contexto de como conseguiu]\n[CTA]",
    hookPattern: "Olha o que [ação] me trouxe...",
    ctaPattern: "Quer receber isso também? Link na bio.",
    format: "story",
    duration: 15,
    examples: "Olha o que chegou no meu WhatsApp depois de 10 minutos no Chamei...\n[Print de 5 orçamentos]\nTudo isso grátis. Sem pagar nada.",
  },
  {
    id: "tmpl_antes_agora",
    name: "Antes eu [dor], agora eu [solução]",
    slug: "antes-agora",
    pillarId: "pillar_social_proof",
    structure: "HOOK: Antes eu [situação ruim]. Agora eu [situação boa].\n[Flashback da dor]\n[Momento da mudança]\n[Vida atual (melhor)]\n[O que fez a diferença]",
    hookPattern: "Antes eu [dor]. Agora eu [benefício].",
    ctaPattern: "Muda sua vida também. Link na bio.",
    format: "reels",
    duration: 30,
    examples: "Antes eu ficava 2h no telefone procurando eletricista.\nAgora eu mando uma mensagem e recebo 5 opções.\nO que mudou? Chamei.",
  },
  {
    id: "tmpl_por_que_escolheram",
    name: "Por que [X] pessoas escolheram [marca]",
    slug: "por-que-escolheram",
    pillarId: "pillar_social_proof",
    structure: "HOOK: Por que [número] pessoas escolheram [marca] em vez de [concorrente]?\n[Motivo 1 - preço/custo]\n[Motivo 2 - experiência]\n[Motivo 3 - resultado]\n[Prova social final]",
    hookPattern: "Por que [número] pessoas largaram [concorrente] e foram pro [marca]?",
    ctaPattern: "Descobre por que. Link na bio.",
    format: "reels",
    duration: 45,
    examples: "Por que 8.000 profissionais escolheram o Chamei?\n1. Grátis (GetNinjas cobra R$80)\n2. Clientes pelo WhatsApp (nada de app)\n3. Orçamento direto (sem intermediário)",
  },
];
